import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ClientProvider } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fr'>
      <body
        className={[
          inter.className,
          'bg-gradient-to-t from-blue-800 to-sky-400 w-full min-h-screen overflow-scroll',
        ].join(' ')}
      >
        <Link href={'/'}>
          <header className='flex justify-center items-center w-full py-4 shadow-md bg-white text-blue-800 sticky font-bold top-0 z-[100]'>
            Disney World
          </header>
        </Link>
        <ClientProvider>
          <main className='text-white p-4'>{children}</main>
        </ClientProvider>
      </body>
    </html>
  );
}
